### ISSUE TITLE
Please point to a more relevant home page

### ISSUE THREAD

**Issue by pcav** [its4land/qgis-boundary-delineation#9]
e.g. https://its4land.com/automate-it-wp5/ instead of the generic company one.
Thanks.

**Comment by SCrommelinck** [comment]
I am not sure if I understand your issue correctly. Could you please clarify the following?

1. Do you refer to the website link in the QGIS plugin metadata? `homepage=https://its4land.com/`?
2. its4land is a H2020 research & innovation project funded by the EU, not a company. The code developed within the project is open source. I developed the plugin as part of this project during my PhD. The link you refer to provides further info on the tool that the plugin is part of (video, publications, images, links). What sort of link would be more suitable? Maybe a link to the GitHub of the entire tool or its [wiki](https://github.com/its4land/delineation-tool/wiki)? I think the [its4land website for the tool](https://its4land.com/automate-it-wp5/) might be a more understandable starting point for a user, as it also has links to the GitHub wiki of the entire tool.

**Comment by pcav** [comment]
I believe https://its4land.com/automate-it-wp5/ is more specific about the plugin, isn't it true?
Cheers.

**Comment by SCrommelinck** [comment]
True, [https://its4land.com/automate-it-wp5/](https://its4land.com/automate-it-wp5/) is a more useful link than [https://its4land.com/](https://its4land.com/). I just replaced it in the plugin's metadata.

**Comment by pcav** [comment]
Thanks
